library(tidyverse)
library(gganimate)
library(ggimage)

p <- ggplot(iris,aes(x=Sepal.Length,y=Sepal.Width)) +
  geom_col() +
  geom_abline()

p + theme(
  aspect.ratio=.5,
  axis.title = element_text(size = 100))
  
  axis.title.x = 0,
  axis.title.x.top = 0,
  axis.title.x.bottom = 0,
  axis.title.y = 0,
  axis.title.y.left = 0,
  axis.title.y.right = 0,
  axis.text = 15,
  axis.text.x = 0,
  axis.text.x.top = 0,
  axis.text.x.bottom = 0,
  axis.text.y = 0,
  axis.text.y.left = 0,
  axis.text.y.right = 0,
  axis.ticks = 20,
  axis.ticks.x = 0,
  axis.ticks.x.top = 0,
  axis.ticks.x.bottom = 0,
  axis.ticks.y = 0,
  axis.ticks.y.left = 0,
  axis.ticks.y.right = 0,
  axis.ticks.length = 0,
  axis.ticks.length.x = 0,
  axis.ticks.length.x.top = 0,
  axis.ticks.length.x.bottom = 0,
  axis.ticks.length.y = 0,
  axis.ticks.length.y.left = 0,
  axis.ticks.length.y.right = 0,
  axis.line = 0,
  axis.line.x = 0,
  axis.line.x.top = 0,
  axis.line.x.bottom = 0,
  axis.line.y = 0,
  axis.line.y.left = 0,
  axis.line.y.right = 0,
  legend.background = 0,
  legend.margin = 0,
  legend.spacing = 0,
  legend.spacing.x = 0,
  legend.spacing.y = 0,
  legend.key = 0,
  legend.key.size = 0,
  legend.key.height = 0,
  legend.key.width = 0,
  legend.text = 0,
  legend.text.align = 0,
  legend.title = element_text(color='green'),
  legend.title.align = 0,
  legend.position = 0,
  legend.direction = 0,
  legend.justification = 0,
  legend.box = 0,
  legend.box.just = 0,
  legend.box.margin = 0,
  legend.box.background = 0,
  legend.box.spacing = 0,
  panel.background = 0,
  panel.border = 0,
  panel.spacing = 0,
  panel.spacing.x = 0,
  panel.spacing.y = 0,
  panel.grid = 0,
  panel.grid.major = 0,
  panel.grid.minor = 0,
  panel.grid.major.x = 0,
  panel.grid.major.y = 0,
  panel.grid.minor.x = 0,
  panel.grid.minor.y = 0,
  panel.ontop = 0,
  plot.background = 0,
  plot.title = 0,
  plot.title.position = 0,
  plot.subtitle = 0,
  plot.caption = 0,
  plot.caption.position = 0,
  plot.tag = 0,
  plot.tag.position = 0,
  plot.margin = 0,
  strip.background = 0,
  strip.background.x = 0,
  strip.background.y = 0,
  strip.clip = 0,
  strip.placement = 0,
  strip.text = 0,
  strip.text.x = 0,
  strip.text.x.bottom = 0,
  strip.text.x.top = 0,
  strip.text.y = 0,
  strip.text.y.left = 0,
  strip.text.y.right = 0,
  strip.switch.pad.grid = 0,
  strip.switch.pad.wrap = 0,
  complete = FALSE,
  validate = TRUE
)

p



pp <- p + theme(aspect.ratio = 2,
         axis.title.x = element_text(face = 'bold',
                                    color='hotpink',
                                    size=16,
                                    hjust = 0,
                                    vjust = -50,
                                    angle = 180,),
        legend.background = element_rect(fill='green'),
        legend.title = element_text(color='pink',
                                    angle=90,
                                    size = 120,
                                    face='italic'
                                    ),
        strip.text = element_text(color='yellow'),
        panel.grid = element_line(size=.1,
                                  color='black'),
        panel.background = element_rect(fill = 'yellow'),
        plot.background = element_rect(fill='black'))
pp
